### ISSUE TITLE
A conflict with System.ValueTuple package

### ISSUE THREAD

**Issue by ShadowJack** [gplumb/NetCrawlerDetect#25]
Hi,

I've tried to add the NetCrawlerDetect in our solution, but it caused multiple dll conflicts and cycled dependencies.

### Problem description
Here is a repro: 
https://github.com/ShadowJack/NetCrawlerDetectConflictExample

The project is compiled successfully after [the first commit](https://github.com/ShadowJack/NetCrawlerDetectConflictExample/commit/3237a6b5eb1c0c478e5534c250a403fbd64657f4), but the build is broken [when I install the NetCrawlerDetect package](https://github.com/ShadowJack/NetCrawlerDetectConflictExample/commit/c85d0d4dd5a2fafe8a4be2f9ae5a8a9255748974).

Here is the build output:
```
1>------ Rebuild All started: Project: NetCrawlerDetectConflict, Configuration: Debug Any CPU ------
1>C:\Users\KPA\Documents\Visual Studio 2019\Projects\NetCrawlerDetectConflict\NetCrawlerDetectConflict\TupleFactory.cs(11,23,11,46): error CS8137: Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?
1>C:\Users\KPA\Documents\Visual Studio 2019\Projects\NetCrawlerDetectConflict\NetCrawlerDetectConflict\TupleFactory.cs(11,23,11,46): error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Also Visual Studio reports another error in a `BotDetector` class:

|Severity|Code|Description|Project|File|Line|Suppression|State|
|---|---|---|---|---|---|---|---|
|Error|CS0731|The type forwarder for type 'System.Text.RegularExpressions.MatchCollection' in assembly 'System' causes a cycle|NetCrawlerDetectConflict|C:\Users\KPA\Documents\Visual Studio 2019\Projects\NetCrawlerDetectConflict\NetCrawlerDetectConflict\BotDetector.cs|14|Active|

### Environment
```
Microsoft Visual Studio Community 2019
Version 16.0.3
VisualStudio.16.Release/16.0.3+28803.352
Microsoft .NET Framework
Version 4.8.03752

ASP.NET and Web Tools 2019   16.0.12313.64372
ASP.NET and Web Tools 2019
ASP.NET Web Frameworks and Tools 2019   16.0.12313.64372
C# Tools   3.0.0-beta4-19218-01+18b0cfb66884840b40491fa0896a8854d68b3959
NuGet Package Manager   5.0.0
...
```

### Possible issue
Many references to .NET Standard dlls are added to the project when I install the NetCrawlerDetect package. All of them have a hintPath to `..\packages\NetCrawlerDetect.0.2.3\lib\netstandard2.0\` folder.
I guess normally it shouldn't be the case, as all .NET standard 2.0 dlls are already present in .NET Framework 4.6.2

Please advise.

**Comment by gplumb** [comment]
My apologies for not replying sooner, I've been offline for the last week or so.

Thank you for the detail, it's incredibly refreshing :-)

The netstandard2.0 folder is a red-herring, since this is common in .net core (if you create a blank .net core library in Visual Studio 2017 and build it, you'll see the same thing).

I'm not sure why this scenario isn't working anymore, I'll have to spend a bit of time digging into it (I won't be able to do this for a few days though as I have family commitments).  I suspect an explicit binding needs to be added - but I won't know for sure until I can spare the time to look.

To avoid blocking you in the meantime, you can always download the source and add a reference to the project in your code (cutting out nuget for now).  It may not be ideal, but it does get you back on track and not tied to my schedule 👍

**Comment by ShadowJack** [comment]
Direct reference to the project works well, thanks.

**Comment by gplumb** [comment]
In updating this package, I decided to revisit this issue and have not been able to reproduce it.  After some google-fu, I have noticed that this may be related to a windows 10 sdk installation.

What version do you have installed (The following registry key should help out: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0)?

**Comment by gplumb** [comment]
OK, after a little more digging, it turns out that I can repro this and it's because of a bad csproj entry. I've just been able to build and include this from .net4.7.x and .net core (as you'd expect) without any of the errors above.

Thank you again for reporting this. The issue is fixed and a new release will be posted shortly.
