### ISSUE TITLE
WebHeaderCollection mismatch in keys style.

### ISSUE THREAD

**Issue by mrjpeterj** [gplumb/NetCrawlerDetect#26]
I might just be doing something wrong here but in all the things that I've tried, my WebHeaderCollection has keys of the form `User-Agent` which doesn't match `USER_AGENT` in your list. 

It's the difference between `-` and `_` .

Now obviously this must work for some people, otherwise it would be obvious that the library never worked, so a quicker pointer would be useful.

Thanks.

**Comment by gplumb** [comment]
Sorry for not responding sooner.

You're quite right, the headers should be '-' and not '_'.  The reason it is an underscore isn't a good one - I simply forgot to transform the character when porting from PHP.

The core functionality of the library does work (and is thoroughly unit-tested, per the upstream project) - I suspect that everyone is calling the code explicitly which is why it's not cropped up yet.  Ie:

```
var detector = new CrawlerDetect();
var result = detector.IsCrawler("Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)");
```

I have fixed the issue and will release an updated package/source shortly.  Thank you for reporting it!
